[build]
  functions = "functions"
  publish = "."

[dev]
  functions = "functions"
  publish = "."
  
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
